module.exports = 
[  
  {
      "routeID": 5,
      "patternID": 2,
      "equipmentID": "3101",
      "tripID": "0",
      "lat": 37.6576,
      "lng": -121.8829,
      "load": 0,
      "capacity": null,
      "blockID": 0,
      "nextStopID": 154,
      "nextStopETA": 1064,
      "nextPatternStopID": 16,
      "scheduleNumber": "06",
      "inService": 1,
      "onSchedule": -7,
      "vehicleType": "Train",
      "trainID": 224,
      "receiveTime": 1549676100000,
      "deadHead": "0",
      "aID": "2133309675",
      "minutesToNextStops": [
        {
          "blockID": 0,
          "stopID": "154",
          "patternStopID": "16",
          "minutes": 9,
          "time": "05:44PM",
          "schedule": "05:37PM",
          "status": "05:44PM",
          "scheduleNumber": "06",
          "statuscolor": "#d58803",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3101",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "153",
          "patternStopID": "17",
          "minutes": 14,
          "time": "05:49PM",
          "schedule": "05:42PM",
          "status": "05:49PM",
          "scheduleNumber": "06",
          "statuscolor": "#d58803",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3101",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "152",
          "patternStopID": "18",
          "minutes": 43,
          "time": "06:18PM",
          "schedule": "06:11PM",
          "status": "06:18PM",
          "scheduleNumber": "06",
          "statuscolor": "#d58803",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3101",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "151",
          "patternStopID": "19",
          "minutes": 55,
          "time": "06:30PM",
          "schedule": "06:23PM",
          "status": "06:30PM",
          "scheduleNumber": "06",
          "statuscolor": "#d58803",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3101",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "150",
          "patternStopID": "20",
          "minutes": 79,
          "time": "06:54PM",
          "schedule": "06:47PM",
          "status": "06:54PM",
          "scheduleNumber": "06",
          "statuscolor": "#d58803",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3101",
          "routeID": 5
        }
      ],
      "direction": "",
      "directionAbbr": ""
    },
    {
      "routeID": 5,
      "patternID": 2,
      "equipmentID": "3102",
      "tripID": null,
      "lat": 37.97884,
      "lng": -121.2843,
      "load": 0,
      "capacity": null,
      "blockID": 0,
      "nextStopID": 0,
      "nextStopETA": -1,
      "nextPatternStopID": 0,
      "scheduleNumber": "NIS",
      "inService": 0,
      "onSchedule": null,
      "vehicleType": "Train",
      "trainID": 0,
      "receiveTime": 1549631892000,
      "deadHead": "0",
      "aID": "2133309724",
      "minutesToNextStops": []
    },
    {
      "routeID": 5,
      "patternID": 1,
      "equipmentID": "3103",
      "tripID": null,
      "lat": 37.73226,
      "lng": -121.6299,
      "load": 0,
      "capacity": null,
      "blockID": 0,
      "nextStopID": 0,
      "nextStopETA": -1,
      "nextPatternStopID": 0,
      "scheduleNumber": "NIS",
      "inService": 0,
      "onSchedule": null,
      "vehicleType": "Train",
      "trainID": 0,
      "receiveTime": 1549641171000,
      "deadHead": "0",
      "aID": "2133309637",
      "minutesToNextStops": []
    },
    {
      "routeID": 5,
      "patternID": 2,
      "equipmentID": "3104",
      "tripID": "0",
      "lat": 37.32883,
      "lng": -121.9029,
      "load": 0,
      "capacity": null,
      "blockID": 0,
      "nextStopID": 158,
      "nextStopETA": 1060,
      "nextPatternStopID": 12,
      "scheduleNumber": "08",
      "inService": 1,
      "onSchedule": 0,
      "vehicleType": "Train",
      "trainID": 226,
      "receiveTime": 1549676108000,
      "deadHead": "0",
      "aID": "2133309673",
      "minutesToNextStops": [
        {
          "blockID": 0,
          "stopID": "158",
          "patternStopID": "12",
          "minutes": 5,
          "time": "05:40PM",
          "schedule": "05:40PM",
          "status": "On Time",
          "scheduleNumber": "08",
          "statuscolor": "#39b139",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3104",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "157",
          "patternStopID": "13",
          "minutes": 14,
          "time": "05:49PM",
          "schedule": "05:49PM",
          "status": "On Time",
          "scheduleNumber": "08",
          "statuscolor": "#39b139",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3104",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "156",
          "patternStopID": "14",
          "minutes": 30,
          "time": "06:05PM",
          "schedule": "06:05PM",
          "status": "On Time",
          "scheduleNumber": "08",
          "statuscolor": "#39b139",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3104",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "155",
          "patternStopID": "15",
          "minutes": 53,
          "time": "06:28PM",
          "schedule": "06:28PM",
          "status": "On Time",
          "scheduleNumber": "08",
          "statuscolor": "#39b139",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3104",
          "routeID": 5
        },
        {
          "blockID": 0,
          "stopID": "154",
          "patternStopID": "16",
          "minutes": 62,
          "time": "06:37PM",
          "schedule": "06:37PM",
          "status": "On Time",
          "scheduleNumber": "08",
          "statuscolor": "#39b139",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3104",
          "routeID": 5
        }
      ],
      "direction": "",
      "directionAbbr": ""
    },
    {
      "routeID": 5,
      "patternID": 2,
      "equipmentID": "3105",
      "tripID": "0",
      "lat": 37.8165,
      "lng": -121.2623,
      "load": 0,
      "capacity": null,
      "blockID": 0,
      "nextStopID": 150,
      "nextStopETA": 1076,
      "nextPatternStopID": 20,
      "scheduleNumber": "04",
      "inService": 1,
      "onSchedule": -9,
      "vehicleType": "Train",
      "trainID": 223,
      "receiveTime": 1549676107000,
      "deadHead": "0",
      "aID": "2133309629",
      "minutesToNextStops": [
        {
          "blockID": 0,
          "stopID": "150",
          "patternStopID": "20",
          "minutes": 21,
          "time": "05:56PM",
          "schedule": "05:47PM",
          "status": "05:56PM",
          "scheduleNumber": "04",
          "statuscolor": "#d58803",
          "track": 3,
          "direction": "",
          "directionAbbr": "",
          "equipmentID": "3105",
          "routeID": 5
        }
      ],
      "direction": "",
      "directionAbbr": ""
    },
    {
      "routeID": 5,
      "patternID": 2,
      "equipmentID": "3106",
      "tripID": null,
      "lat": 37.97881,
      "lng": -121.2844,
      "load": 0,
      "capacity": null,
      "blockID": 0,
      "nextStopID": 0,
      "nextStopETA": -1,
      "nextPatternStopID": 0,
      "scheduleNumber": "NIS",
      "inService": 0,
      "onSchedule": null,
      "vehicleType": "Train",
      "trainID": 0,
      "receiveTime": 1549523595000,
      "deadHead": "0",
      "aID": "2133309685",
      "minutesToNextStops": []
    }
]